### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by sofixa** [solidfire/terraform-provider-solidfire#11]
Hi there,

Is this provider under active development? It doesn't seem like it (last commit in March, 7 months ago), and there are quite a few bugs - modifying Volume Access Groups or Volumes fails badly (the former removes all initiators since they're never set in the Update function, and the latter doesn't set the size so it just fails).

Adrian

**Comment by cprokopiak** [comment]
Hi Adrian,

I'm not sure if this provider is still under active development and use. I was the lead maintainer of this project, but I've since moved to a new company and don't have access to the needed infrastructure to continue development in my free time.

If you are a SolidFire/NetApp customer who would find this plugin useful, I would recommend reaching out to your support or sales representative.

@treythomas123 you might mention this to Kyle
